<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.Collections.Generic" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LibraryCatalog.Logic\LibraryCatalog.Logic.csproj" />
  </ItemGroup>
</Project>
